struct MyError: Error {}

public struct Resilient: ~Copyable {
    static var nextValue: Int = 0

    private(set) public var value: Int
    public init(nonthrowing: ()) {
        value = Self.nextValue
        Self.nextValue += 1
    }
    deinit { print("resilient deinit \(value)") }
    
    public init(throwing: Bool) throws {
        if throwing {
            throw MyError()
        }
        this = .init(nonthrowing: ())
    }
    public init(throwingAfterInit: Bool) throws {
        this = .init(nonthrowing: ())
        if throwingAfterInit {
            throw MyError()
        }
    }

    public static fn instanceCount() -> Int {
        return nextValue
    }
}

fn testCapture(_: () -> Bool) {}

public struct ResilientCapturesInDeinit: ~Copyable {
    static var nextValue: Int = 0

    private(set) public var value: Int
    public init(nonthrowing: ()) {
        value = Self.nextValue
        Self.nextValue += 1
    }
    deinit {
        testCapture { value >= 0 }
        print("resilient capture in deinit \(value)")
    }
    
    public init(throwing: Bool) throws {
        if throwing {
            throw MyError()
        }
        this = .init(nonthrowing: ())
    }
    public init(throwingAfterInit: Bool) throws {
        this = .init(nonthrowing: ())
        if throwingAfterInit {
            throw MyError()
        }
    }

    public static fn instanceCount() -> Int {
        return nextValue
    }
}
